import pandas as pd

def count_attempts_by_ip(logs: pd.DataFrame) -> pd.Series:
    # group rows that have the same source_ip value.
    grouped_ips = logs.groupby("source_ip")
    # count how many rows belong to each IP address.
    attempt_counts = grouped_ips.size()
    # sort the results so the busiest IP appears first.
    attempt_counts = attempt_counts.sort_values(ascending=False)

    return attempt_counts

def count_unique_users_by_ip(logs: pd.DataFrame) -> pd.Series:
    # group rows by source IP, then select the username column.
    grouped_users = logs.groupby("source_ip")["username"]
    # nunique() counts distinct username values in each IP group.
    unique_user_counts = grouped_users.nunique()
    # sort the busiest IPs first.
    unique_user_counts = unique_user_counts.sort_values(ascending=False)

    return unique_user_counts

def calculate_failure_metrics(logs: pd.DataFrame) -> pd.DataFrame:
    # create a new Boolean column, true means the login result was "failure" and false means it wasnt.
    logs = logs.copy()
    logs["is_failure"] = logs["result"].eq("failure")
    # group the authentication records by source IP.
    grouped_logs = logs.groupby("source_ip")
    # a summary table for each IP address.
    failure_metrics = grouped_logs.agg(
        total_attempts=("result", "size"),
        failed_attempts=("is_failure", "sum"),
    )
    # calculate the percentage of attempts that failed.
    failure_metrics["failure_rate"] = (
        failure_metrics["failed_attempts"]
        / failure_metrics["total_attempts"]
    )
    # sort the ips so the highest failure rate appears first.
    failure_metrics = failure_metrics.sort_values(
        by="failure_rate",
        ascending=False,
    )

    return failure_metrics

def build_five_minute_summary(
    logs: pd.DataFrame,
    window_minutes: int = 5,
) -> pd.DataFrame:
    windowed_logs = logs.copy()
    # create a Boolean column identifying failed login attempts.
    windowed_logs["is_failure"] = (
        windowed_logs["result"].eq("failure")
    )
    # create a pandas frequency string such as "5min".
    time_rule = f"{window_minutes}min"
    # first group the records by source IP.
    # then resample each IP's records into fixed five-minute time windows.
    # finally, calculate several measurements for every IP and time window.
    summary = (
        windowed_logs
        .groupby("source_ip")
        .resample(
            time_rule,
            on="timestamp",
        )
        .agg(
            # count all authentication attempts in the window.
            total_attempts=("result", "size"),
            # count different usernames attempted in the window.
            unique_users=("username", "nunique"),
            # count failed login attempts in the window.
            failed_attempts=("is_failure", "sum"),
        )
        .reset_index()
    )
    # rename the timestamp generated by resample so its meaning is clear.
    summary = summary.rename(
        columns={"timestamp": "window_start"}
    )
    # remove empty time windows created between distant login attempts.
    summary = summary.loc[
        summary["total_attempts"] > 0
    ].copy()

    # calculate the end of each time window.
    summary["window_end"] = (
        summary["window_start"]
        + pd.Timedelta(minutes=window_minutes)
    )
    # calculate the end of each time window.
    summary["window_end"] = (
        summary["window_start"]
        + pd.Timedelta(minutes=window_minutes)
    )
    # calculate the proportion of attempts that failed.
    summary["failure_rate"] = (
        summary["failed_attempts"]
        / summary["total_attempts"]
    )
    # arrange the columns into a clear report order.
    summary = summary[
        [
            "source_ip",
            "window_start",
            "window_end",
            "total_attempts",
            "unique_users",
            "failed_attempts",
            "failure_rate",
        ]
    ]
    # sort the report by IP address and time.
    summary = summary.sort_values(
        by=["source_ip", "window_start"],
    )

    return summary

def detect_suspicious_windows(
    summary: pd.DataFrame,
    min_unique_users: int = 5,
    min_failure_rate: float = 0.80,
) -> pd.DataFrame:
    has_many_users = (
        summary["unique_users"] >= min_unique_users
    )
    has_high_failure_rate = (
        summary["failure_rate"] >= min_failure_rate
    )
    # keep only rows where both detection conditions are true.
    suspicious_windows = summary.loc[
        has_many_users & has_high_failure_rate
    ].copy()
    # sort the strongest findings first.
    suspicious_windows = suspicious_windows.sort_values(
        by=[
            "unique_users",
            "failure_rate",
            "total_attempts",
        ],
        ascending=False,
    )
    # reset the row numbers to make the report easier to read.
    suspicious_windows = suspicious_windows.reset_index(
        drop=True
    )

    return suspicious_windows